### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/JsonFlyweight#3]
In https://github.com/kazurayam/JsonFlyweight/blob/master/lib/src/test/java/com/kazurayam/jsonflyweight/FlyPrettyPrinterTest.java I added a test case:

```
@Test
    public void test_pp_large_HAR() throws IOException {
        Path har180mb = locateLargeHAR();
        InputStream is = Files.newInputStream(har180mb);
        Path dir = too.cleanMethodOutputDirectory("test_pp_large_HAR");
        Path out = dir.resolve("out.json");
        OutputStream os = Files.newOutputStream(out);
        int numLines = FlyPrettyPrinter.prettyPrint(is, os);
        assertThat(out).exists();
        assertThat(out.toFile().length()).isGreaterThan(11 * 1000 * 1000);
    }

    private Path locateLargeHAR() {
        Path userHome = Paths.get(System.getProperty("user.home"));
        Path hostProject = userHome.resolve("katalon-workspace/BrowserMobProxyInKatalonStudio");
        Path harFile = hostProject.resolve("work/TS3_process_large_HAR.har");
        return harFile;
    }
```

The HAR file as input is large. 180 MB. It has only a single line. It has no NewLine characters.

When I ran this test case I got an error "java.lang.OutOfMemoryError: Java heap space"

```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:686)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:228)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:372)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at com.kazurayam.jsonflyweight.FlyPrettyPrinter.prettyPrint(FlyPrettyPrinter.java:108)
	at com.kazurayam.jsonflyweight.FlyPrettyPrinter.prettyPrint(FlyPrettyPrinter.java:55)
```

`FlyPrettyPrinter.java:108` is as follows:

```  
        String line;
        while ((line = br.readLine()) != null) {
```

Aha!  180 MB characters are read into a single String variable! and then a OutOfMemoryError occured!

**Comment by kazurayam** [comment]
Currently I have this fragment:
```
static int prettyPrint(Reader uglyJSON, Writer prettyPrintedJSON) throws IOException {
        BufferedReader br = new BufferedReader(uglyJSON);
        PrintWriter pw = new PrintWriter(new BufferedWriter(prettyPrintedJSON));
```

How stupid!

**Comment by kazurayam** [comment]
v0.1.3 fixed this
